/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Dynamic Theme Semantic Design System
        "surface": "rgb(var(--bg-surface-rgb) / <alpha-value>)",
        "surface-dim": "rgb(var(--bg-sidebar-rgb) / <alpha-value>)",
        "surface-bright": "rgb(var(--bg-surface-bright-rgb) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--bg-rail-rgb) / <alpha-value>)",
        "surface-container-low": "rgb(var(--bg-sidebar-rgb) / <alpha-value>)",
        "surface-container": "rgb(var(--bg-card-rgb) / <alpha-value>)",
        "surface-container-high": "rgb(var(--bg-card-hover-rgb) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--bg-card-hover-rgb) / <alpha-value>)",
        "on-surface": "rgb(var(--txt-primary-rgb) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--txt-secondary-rgb) / <alpha-value>)",
        "inverse-surface": "rgb(var(--txt-primary-rgb) / <alpha-value>)",
        "inverse-on-surface": "rgb(var(--bg-surface-rgb) / <alpha-value>)",
        "outline": "rgb(var(--txt-muted-rgb) / <alpha-value>)",
        "outline-variant": "var(--border-glass)",
        "surface-tint": "rgb(var(--accent-primary-rgb) / <alpha-value>)",
        "primary": "rgb(var(--accent-primary-rgb) / <alpha-value>)",
        "on-primary": "#0d0c11",
        "primary-container": "rgb(var(--accent-primary-rgb) / 0.15)",
        "on-primary-container": "rgb(var(--accent-primary-rgb) / <alpha-value>)",
        "inverse-primary": "rgb(var(--accent-primary-rgb) / <alpha-value>)",
        "secondary": "rgb(var(--accent-secondary-rgb) / <alpha-value>)",
        "on-secondary": "#ffffff",
        "secondary-container": "rgb(var(--accent-secondary-rgb) / 0.15)",
        "on-secondary-container": "rgb(var(--accent-secondary-rgb) / <alpha-value>)",
        "tertiary": "rgb(var(--accent-emerald-rgb) / <alpha-value>)",
        "on-tertiary": "#ffffff",
        "tertiary-container": "rgb(var(--accent-emerald-rgb) / 0.15)",
        "on-tertiary-container": "rgb(var(--accent-emerald-rgb) / <alpha-value>)",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "rgb(var(--accent-primary-rgb) / 0.2)",
        "primary-fixed-dim": "rgb(var(--accent-primary-rgb) / 0.1)",
        "on-primary-fixed": "rgb(var(--txt-primary-rgb) / <alpha-value>)",
        "on-primary-fixed-variant": "rgb(var(--txt-secondary-rgb) / <alpha-value>)",
        "background": "rgb(var(--bg-app-rgb) / <alpha-value>)",
        "on-background": "rgb(var(--txt-primary-rgb) / <alpha-value>)",

        // Dynamic theme bindings
        theme: {
          main: 'rgb(var(--text-main-rgb) / <alpha-value>)',
          muted: 'rgb(var(--text-muted-rgb) / <alpha-value>)',
        },
        accent: {
          primary: 'rgb(var(--accent-primary-rgb) / <alpha-value>)',
          secondary: 'rgb(var(--accent-secondary-rgb) / <alpha-value>)',
        },
        status: {
          online: 'rgb(var(--status-online-rgb) / <alpha-value>)',
          offline: 'rgb(var(--status-offline-rgb) / <alpha-value>)',
        },
        glass: {
          surface: 'rgb(var(--glass-surface-rgb) / <alpha-value>)',
          border: 'rgb(var(--glass-border-rgb) / <alpha-value>)',
        },
      },
      fontFamily: {
        sans: ['"Outfit"', '"Plus Jakarta Sans"', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'sans-serif'],
      },
      fontSize: {
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-lg": ["17px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        'glass-level-1': '0 8px 32px 0 rgba(0, 0, 0, 0.36)',
        'glass-level-2': '0 20px 48px 0 rgba(0, 0, 0, 0.55), inset 0 1px 0 0 rgba(255, 255, 255, 0.15)',
        'bubble-out': '0 4px 14px rgba(99, 102, 241, 0.3)',
        'bubble-in': '0 2px 8px rgba(15, 23, 42, 0.05)',
        'specular': 'inset 0 1px 1px rgba(255, 255, 255, 0.22)',
      },
      spacing: {
        88: '22rem',
        "gutter": "1.5rem",
        "gutter-mobile": "0.75rem",
        "margin": "3rem",
        "margin-mobile": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'bounce-soft': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      animation: {
        'fade-in': 'fadeIn 0.2s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-up': 'slideUp 0.25s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'scale-in': 'scaleIn 0.2s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'message-in': 'messageIn 0.2s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.96)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        messageIn: {
          '0%': { opacity: '0', transform: 'translateY(8px) scale(0.98)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
      },
    },
  },
  plugins: [],
}
