/**
 * Curated High-Speed GIF & Animated Sticker Library for Pulse Messenger
 * Categorized and indexed for instant search and instant loading.
 */

export const GIF_CATEGORIES = [
  { id: "all", label: "🔥 Trending" },
  { id: "laugh", label: "😂 Laugh" },
  { id: "love", label: "❤️ Love" },
  { id: "thumbsup", label: "👍 Thumbs Up" },
  { id: "party", label: "🎉 Party" },
  { id: "dance", label: "💃 Dance" },
  { id: "shocked", label: "😲 Shocked" },
  { id: "anime", label: "✨ Anime" },
  { id: "animals", label: "🐱 Cute" },
  { id: "cool", label: "😎 Cool" },
  { id: "gaming", label: "🎮 Gaming" },
  { id: "sad", label: "😢 Sad" },
];

export const GIF_ITEMS = [
  // Trending / Classics
  {
    id: "g_trend_1",
    title: "Excited Happy Dance",
    category: "trending",
    tags: ["happy", "dance", "excited", "celebrate", "joy", "fun"],
    url: "https://media.giphy.com/media/3o7TKSjRrfIPjeiVyM/giphy.gif",
    preview: "https://media.giphy.com/media/3o7TKSjRrfIPjeiVyM/200w.gif",
  },
  {
    id: "g_trend_2",
    title: "Applause Clapping",
    category: "thumbsup",
    tags: ["clap", "applause", "bravo", "good job", "agree", "yes"],
    url: "https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif",
    preview: "https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/200w.gif",
  },
  {
    id: "g_trend_3",
    title: "Shocked Mind Blown",
    category: "shocked",
    tags: ["mind blown", "shocked", "omg", "wow", "explosion", "crazy"],
    url: "https://media.giphy.com/media/26AHONQ79FdWZhAI0/giphy.gif",
    preview: "https://media.giphy.com/media/26AHONQ79FdWZhAI0/200w.gif",
  },
  {
    id: "g_trend_4",
    title: "Awesome Thumbs Up",
    category: "thumbsup",
    tags: ["thumbs up", "nice", "great", "cool", "approved", "ok", "yes"],
    url: "https://media.giphy.com/media/3oEjI6SIIHBdRxXI40/giphy.gif",
    preview: "https://media.giphy.com/media/3oEjI6SIIHBdRxXI40/200w.gif",
  },
  {
    id: "g_trend_5",
    title: "Popcorn Watching Drama",
    category: "trending",
    tags: ["popcorn", "eating", "drama", "watching", "movie", "tea", "chill"],
    url: "https://media.giphy.com/media/xT9IgG50Fb7Mi0prBC/giphy.gif",
    preview: "https://media.giphy.com/media/xT9IgG50Fb7Mi0prBC/200w.gif",
  },
  {
    id: "g_trend_6",
    title: "Snoop Dogg Dance",
    category: "dance",
    tags: ["snoop", "dance", "groove", "music", "cool", "vibe"],
    url: "https://media.giphy.com/media/GeimqsH0TLDt4tScGw/giphy.gif",
    preview: "https://media.giphy.com/media/GeimqsH0TLDt4tScGw/200w.gif",
  },
  {
    id: "g_trend_7",
    title: "Leonardo DiCaprio Toast",
    category: "cool",
    tags: ["cheers", "toast", "leo", "great gatsby", "respect", "drink"],
    url: "https://media.giphy.com/media/GCLlQnV7Ej0U8/giphy.gif",
    preview: "https://media.giphy.com/media/GCLlQnV7Ej0U8/200w.gif",
  },
  {
    id: "g_trend_8",
    title: "Homer Simpson Disappearing in Bushes",
    category: "trending",
    tags: ["homer", "simpsons", "bush", "awkward", "bye", "leave", "disappear"],
    url: "https://media.giphy.com/media/COYGe9rZwsneg/giphy.gif",
    preview: "https://media.giphy.com/media/COYGe9rZwsneg/200w.gif",
  },

  // Laugh / Funny
  {
    id: "g_laugh_1",
    title: "Laughing Hard Tears",
    category: "laugh",
    tags: ["laugh", "funny", "lol", "lmao", "rofl", "hilarious", "joke"],
    url: "https://media.giphy.com/media/10JhviFuU2gWD6/giphy.gif",
    preview: "https://media.giphy.com/media/10JhviFuU2gWD6/200w.gif",
  },
  {
    id: "g_laugh_2",
    title: "Cat Laughing",
    category: "laugh",
    tags: ["cat", "laugh", "meme", "funny", "lol", "animal"],
    url: "https://media.giphy.com/media/unQ3IJU2RG7DO/giphy.gif",
    preview: "https://media.giphy.com/media/unQ3IJU2RG7DO/200w.gif",
  },
  {
    id: "g_laugh_3",
    title: "Ryan Gosling Laughing",
    category: "laugh",
    tags: ["laugh", "ryan gosling", "giggle", "smirk", "funny"],
    url: "https://media.giphy.com/media/3o7btUg31OCi0NXdkY/giphy.gif",
    preview: "https://media.giphy.com/media/3o7btUg31OCi0NXdkY/200w.gif",
  },
  {
    id: "g_laugh_4",
    title: "Steve Carell Laugh Laugh",
    category: "laugh",
    tags: ["steve carell", "office", "michael scott", "laugh", "smile"],
    url: "https://media.giphy.com/media/agwRgmVDJceZO/giphy.gif",
    preview: "https://media.giphy.com/media/agwRgmVDJceZO/200w.gif",
  },
  {
    id: "g_laugh_5",
    title: "Minion Giggling",
    category: "laugh",
    tags: ["minion", "laugh", "cute", "funny", "cartoon"],
    url: "https://media.giphy.com/media/ZqlvCTNHpqrio/giphy.gif",
    preview: "https://media.giphy.com/media/ZqlvCTNHpqrio/200w.gif",
  },

  // Love / Hearts
  {
    id: "g_love_1",
    title: "Heart Eyes Love",
    category: "love",
    tags: ["love", "hearts", "adore", "crush", "romantic", "kiss"],
    url: "https://media.giphy.com/media/R6gVNAxj2vzSaBaR2t/giphy.gif",
    preview: "https://media.giphy.com/media/R6gVNAxj2vzSaBaR2t/200w.gif",
  },
  {
    id: "g_love_2",
    title: "Cat Heart Hug",
    category: "love",
    tags: ["cat", "hug", "love", "cuddle", "sweet", "wholesome"],
    url: "https://media.giphy.com/media/MDJ9IbxxvDUQM/giphy.gif",
    preview: "https://media.giphy.com/media/MDJ9IbxxvDUQM/200w.gif",
  },
  {
    id: "g_love_3",
    title: "Blowing a Kiss",
    category: "love",
    tags: ["kiss", "love", "flirt", "sweet", "bye", "muah"],
    url: "https://media.giphy.com/media/3o7TKoWXm3okO1kgHC/giphy.gif",
    preview: "https://media.giphy.com/media/3o7TKoWXm3okO1kgHC/200w.gif",
  },
  {
    id: "g_love_4",
    title: "Puppy Heart Eyes",
    category: "love",
    tags: ["dog", "puppy", "love", "cute", "sweet"],
    url: "https://media.giphy.com/media/v4zKO4kK0v1kY/giphy.gif",
    preview: "https://media.giphy.com/media/v4zKO4kK0v1kY/200w.gif",
  },

  // Party / Celebration
  {
    id: "g_party_1",
    title: "Confetti Celebration Party",
    category: "party",
    tags: ["party", "celebrate", "confetti", "yay", "hooray", "win"],
    url: "https://media.giphy.com/media/l4KhQo2MESJkc6HyM/giphy.gif",
    preview: "https://media.giphy.com/media/l4KhQo2MESJkc6HyM/200w.gif",
  },
  {
    id: "g_party_2",
    title: "Dancing Parrot Rave",
    category: "party",
    tags: ["parrot", "party", "rave", "dance", "disco", "vibing"],
    url: "https://media.giphy.com/media/l3q2zVr6ET95U3ITm/giphy.gif",
    preview: "https://media.giphy.com/media/l3q2zVr6ET95U3ITm/200w.gif",
  },
  {
    id: "g_party_3",
    title: "Champagne Celebration",
    category: "party",
    tags: ["champagne", "celebrate", "party", "victory", "cheers", "win"],
    url: "https://media.giphy.com/media/g9582DNuQppxC/giphy.gif",
    preview: "https://media.giphy.com/media/g9582DNuQppxC/200w.gif",
  },

  // Dance / Vibing
  {
    id: "g_dance_1",
    title: "Carlton Dance",
    category: "dance",
    tags: ["carlton", "fresh prince", "dance", "happy", "groove"],
    url: "https://media.giphy.com/media/pa37AAGzKXoek/giphy.gif",
    preview: "https://media.giphy.com/media/pa37AAGzKXoek/200w.gif",
  },
  {
    id: "g_dance_2",
    title: "Baby Groot Dancing",
    category: "dance",
    tags: ["groot", "marvel", "dance", "cute", "music"],
    url: "https://media.giphy.com/media/14bhmZtBNhVnIk/giphy.gif",
    preview: "https://media.giphy.com/media/14bhmZtBNhVnIk/200w.gif",
  },
  {
    id: "g_dance_3",
    title: "Cat Head Bop Vibing",
    category: "dance",
    tags: ["cat", "vibing", "head bop", "music", "beat", "song"],
    url: "https://media.giphy.com/media/jpbnoe3UIa8TU8LM13/giphy.gif",
    preview: "https://media.giphy.com/media/jpbnoe3UIa8TU8LM13/200w.gif",
  },

  // Anime
  {
    id: "g_anime_1",
    title: "Anime Yay Excited",
    category: "anime",
    tags: ["anime", "excited", "sparkles", "happy", "kawaii"],
    url: "https://media.giphy.com/media/artj92V8o75VPL7AeQ/giphy.gif",
    preview: "https://media.giphy.com/media/artj92V8o75VPL7AeQ/200w.gif",
  },
  {
    id: "g_anime_2",
    title: "Anime Cute Headpat",
    category: "anime",
    tags: ["anime", "headpat", "pat", "cute", "wholesome", "kawaii"],
    url: "https://media.giphy.com/media/L2QgkdeUgmvf5WAUEg/giphy.gif",
    preview: "https://media.giphy.com/media/L2QgkdeUgmvf5WAUEg/200w.gif",
  },
  {
    id: "g_anime_3",
    title: "Anime Shocked Face",
    category: "anime",
    tags: ["anime", "shocked", "what", "omg", "reaction"],
    url: "https://media.giphy.com/media/3oKIPbNb1v65h88mCA/giphy.gif",
    preview: "https://media.giphy.com/media/3oKIPbNb1v65h88mCA/200w.gif",
  },

  // Cute Animals
  {
    id: "g_animal_1",
    title: "Happy Golden Retriever",
    category: "animals",
    tags: ["dog", "puppy", "happy", "smile", "cute", "golden retriever"],
    url: "https://media.giphy.com/media/mCRJDo24UvJMA/giphy.gif",
    preview: "https://media.giphy.com/media/mCRJDo24UvJMA/200w.gif",
  },
  {
    id: "g_animal_2",
    title: "Cat Typing on Keyboard",
    category: "animals",
    tags: ["cat", "typing", "coding", "work", "keyboard", "hacker"],
    url: "https://media.giphy.com/media/JIX9t2j0ZTN9S/giphy.gif",
    preview: "https://media.giphy.com/media/JIX9t2j0ZTN9S/200w.gif",
  },
  {
    id: "g_animal_3",
    title: "Panda Roll Cute",
    category: "animals",
    tags: ["panda", "roll", "cute", "funny", "bear"],
    url: "https://media.giphy.com/media/EatwJZRUIv41G/giphy.gif",
    preview: "https://media.giphy.com/media/EatwJZRUIv41G/200w.gif",
  },

  // Cool & Gaming
  {
    id: "g_cool_1",
    title: "Sunglasses Deal With It",
    category: "cool",
    tags: ["deal with it", "sunglasses", "cool", "boss", "swag"],
    url: "https://media.giphy.com/media/1jnyRP4DorCh2/giphy.gif",
    preview: "https://media.giphy.com/media/1jnyRP4DorCh2/200w.gif",
  },
  {
    id: "g_gaming_1",
    title: "Mario Victory Win",
    category: "gaming",
    tags: ["mario", "nintendo", "gaming", "win", "victory", "gamer"],
    url: "https://media.giphy.com/media/atQF1zaSGq8s8/giphy.gif",
    preview: "https://media.giphy.com/media/atQF1zaSGq8s8/200w.gif",
  },
  {
    id: "g_gaming_2",
    title: "Gamer Intense Focus",
    category: "gaming",
    tags: ["gamer", "gaming", "focus", "play", "controller", "pc"],
    url: "https://media.giphy.com/media/3oKIPnAiaMCws8nOsE/giphy.gif",
    preview: "https://media.giphy.com/media/3oKIPnAiaMCws8nOsE/200w.gif",
  },

  // Sad / Cry
  {
    id: "g_sad_1",
    title: "Dramatic Crying River",
    category: "sad",
    tags: ["sad", "cry", "crying", "tears", "upset", "drama"],
    url: "https://media.giphy.com/media/d2lcHJTG5Tscg/giphy.gif",
    preview: "https://media.giphy.com/media/d2lcHJTG5Tscg/200w.gif",
  },
  {
    id: "g_sad_2",
    title: "Sad Cat Crying Meme",
    category: "sad",
    tags: ["cat", "sad", "crying", "meme", "pain"],
    url: "https://media.giphy.com/media/OPU6wzx8JrHna/giphy.gif",
    preview: "https://media.giphy.com/media/OPU6wzx8JrHna/200w.gif",
  },
];

export const STICKER_ITEMS = [
  {
    id: "stk_1",
    title: "Sparkling Fire Heart",
    category: "love",
    tags: ["heart", "fire", "love", "flame", "sticker"],
    url: "https://media.giphy.com/media/26FLdmIp6wJr91JAI/giphy.gif",
    preview: "https://media.giphy.com/media/26FLdmIp6wJr91JAI/200w.gif",
  },
  {
    id: "stk_2",
    title: "Rainbow Neon Wow",
    category: "shocked",
    tags: ["wow", "rainbow", "neon", "cool", "sticker"],
    url: "https://media.giphy.com/media/26u4cqiYI30juCOGY/giphy.gif",
    preview: "https://media.giphy.com/media/26u4cqiYI30juCOGY/200w.gif",
  },
  {
    id: "stk_3",
    title: "Cute Dancing Boba",
    category: "dance",
    tags: ["boba", "tea", "cute", "dance", "sticker"],
    url: "https://media.giphy.com/media/3oz8xLd9DJq2l2VFtu/giphy.gif",
    preview: "https://media.giphy.com/media/3oz8xLd9DJq2l2VFtu/200w.gif",
  },
  {
    id: "stk_4",
    title: "Thumbs Up Glow",
    category: "thumbsup",
    tags: ["thumbs up", "glow", "yes", "nice", "sticker"],
    url: "https://media.giphy.com/media/26ufdipQqU2lhNA4g/giphy.gif",
    preview: "https://media.giphy.com/media/26ufdipQqU2lhNA4g/200w.gif",
  },
  {
    id: "stk_5",
    title: "Party Popper Stars",
    category: "party",
    tags: ["party", "stars", "celebrate", "popper", "sticker"],
    url: "https://media.giphy.com/media/26tPplGWjN0xLybiU/giphy.gif",
    preview: "https://media.giphy.com/media/26tPplGWjN0xLybiU/200w.gif",
  },
  {
    id: "stk_6",
    title: "Shining Star Kawaii",
    category: "cool",
    tags: ["star", "kawaii", "shine", "sparkle", "sticker"],
    url: "https://media.giphy.com/media/26tP41fh76vmLO3iU/giphy.gif",
    preview: "https://media.giphy.com/media/26tP41fh76vmLO3iU/200w.gif",
  },
  {
    id: "stk_7",
    title: "Cool Pixel Glasses",
    category: "cool",
    tags: ["glasses", "pixel", "cool", "swag", "sticker"],
    url: "https://media.giphy.com/media/3o7TKSha51ATTx9KzC/giphy.gif",
    preview: "https://media.giphy.com/media/3o7TKSha51ATTx9KzC/200w.gif",
  },
  {
    id: "stk_8",
    title: "Laughing Emoji Spin",
    category: "laugh",
    tags: ["laugh", "emoji", "lol", "funny", "sticker"],
    url: "https://media.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif",
    preview: "https://media.giphy.com/media/3o7abKhOpu0NwenH3O/200w.gif",
  },
];
